.comp ReadOnlyPattern : Pattern{
    NAME("Read-only field.")

    DESCRIPTION("Field is loaded but never used.")

    SEVERITY(MEDIUM)

    applicable(unitId, "unknown") :-
        load(unitId, _).



    compliance(unitId, "unknown_line", "") :-
        load(unitId, _),
        followsStep(followID, unitId),
        !proc(followID, _).
        
    violation(unitId, "unknown_line", "") :-
        applicable(unitId, _),
        c = count : { followsStep(_, unitId)},
        c = 1.

}


